controllers:
    resource: ../src/Controller/
    type: attribute
# config/routes.yaml
Login:
    path: /Login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LoginController::index


Logout:
    path: /Logout
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LogoutController::index




    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\LoginController